package com.example.recipeapp.data

import androidx.room.Entity
import androidx.room.PrimaryKey
import androidx.room.TypeConverters

/**
 * Entity class representing a recipe in the database.
 *
 * @property id Unique identifier for the recipe. Auto-generated by the database.
 * @property title Title of the recipe.
 * @property ingredients Ingredients of the recipe. //TODO changed type
 * @property instructions Cooking instructions for the recipe. //TODO changed type
 * @property image Resource ID of the image associated with the recipe.
 */
@Entity(tableName = "recipe_table")
data class Recipe(
    @PrimaryKey(autoGenerate = true)
    val id : Int = 0,
    val title: String,
    val ingredients: HashMap<String, Int>,
    val instructions: String,
    val image: Int)

@Entity(tableName = "favorite_table")
data class Favorite(
    @PrimaryKey(autoGenerate = true)
    val id : Int = 0,
    val title: String,
    val description: String,
    val image: Int)

